# Generated by Django 3.0.6 on 2020-06-18 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_auto_20200618_1253'),
        ('lists', '0002_auto_20200618_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='rooms',
            field=models.ManyToManyField(related_name='lists', to='rooms.Room'),
        ),
    ]
